### ISSUE TITLE
OOM?  Plus map density

### ISSUE THREAD

**Issue by agroce** [andreafioraldi/weizz-fuzzer#4]
Trying to fuzz the solc compiler (which I've been fuzzing with AFL for months now), I got weizz to run but after only a few execs it stops thus.  Any guesses about the OOM?  Could upping the -m parameter help here, or is this at the level of memory available to the docker container (which is, IIRC, a couple of GB) -- does weizz need substantially more memory than AFL to run?

Also, the map density is at a level that would be a red flag with AFL, and suggest recompiling with AFL_INST_RATIO set to 10, is there any way to deal with map density here where you don't change compilation, just rely on QEMU?

![Screen Shot 2020-08-03 at 6 31 18 AM](https://user-images.githubusercontent.com/967816/89188122-10dad480-d553-11ea-8041-473a15645289.png)

**Comment by agroce** [comment]
(command line I used is shown as well as the fuzzer abort)

**Comment by agroce** [comment]
the stability is also surprising, given that this target (solfuzzer, the fuzzer executable for the compiler, which catches various bugs and compiles stdin) has 100% stability every time I've run it under AFL or my modified AFL.  That's all compiler instrumentation, not QEMU, of course.

**Comment by andreafioraldi** [comment]
Yes, weizz needs much more memory. In the target, the cmp table is 20 megabytes (not always used so just mapped memory), in the fuzzer, the dependencies table can grow up to some gigabytes in the worst case.

For the map, do not set WEIZZ_CTX_SENSITIVE if the target is huge. Increase MAP_SIZE in include/config.h and recompile the fuzzer. Now I just pushed the support to WEIZZ_INST_RATIO for Qemu, use it just like AFL.

Btw, Solidity is a programming language, weizz targets binary formats, probably you will not get much benefit to use weizz instead of AFL.

**Comment by andreafioraldi** [comment]
If you want just the cmp bypassing, look at https://github.com/AFLplusplus/AFLplusplus/blob/stable/llvm_mode/README.cmplog.md

**Comment by agroce** [comment]
Thanks!

Yeah, I'm guessing this will not be too useful here, but want to actually see how it performs.
